spring.application.name=game-zone
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

spring.messages.basename=messages
spring.messages.encoding=UTF-8


# Configuraci\uFFFDn de Hibernate y JPA
# Define c\uFFFDmo Hibernate gestiona la creaci\uFFFDn y actualizaci\uFFFDn del esquema de la base de datos
# "none" no actualiza la base de datos de forma automatica y se deja la gesti\uFFFDn manual en schema.sql y data.sql
spring.jpa.hibernate.ddl-auto=none


# Muestra las consultas SQL generadas en la consola
spring.jpa.show-sql=true


# Formatea las consultas SQL para que sean m\uFFFDs legibles en la consola
spring.jpa.properties.hibernate.format_sql=true


# Dialecto espec\uFFFDfico de Hibernate para MariaDB (es compatible con MySQL)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# Inicializaci\uFFFDn de la base de datos
# Esta propiedad asegura que Spring Boot ejecuta los archivos la estrucutra (schema.sql) y de carga de datos (data.sql) al inicio
spring.sql.init.mode=always


# Configuraci\uFFFDn de los logs del datasource
# Muestra detalles adicionales sobre la conexi\uFFFDn a la base de datos
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG


# N\uFFFDmero m\uFFFDximo de conexiones que puede abrir el pool de conexiones
spring.datasource.hikari.maximum-pool-size=10